[package]
name = "seiton-metadata-exiftool"
description = "ExifTool-based metadata provider (stay_open process)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]

[lints]
workspace = true
