// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileView } from "./FileView";
import type { RatingSource } from "./RatingSource";

/**
 * A shot: one or more files sharing a name, plus its metadata.
 */
export type AssetView = { id: string, deviceId: string, name: string, 
/**
 * Local capture time `YYYY-MM-DDTHH:MM:SS` (EXIF has no time zone).
 */
captureTime: string | null, files: Array<FileView>, 
/**
 * Effective rating 0–5, `null` when unrated.
 */
rating: number | null, ratingSource: RatingSource | null, 
/**
 * Already imported to a destination.
 */
imported: boolean, };
