// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransportView } from "./TransportView";

/**
 * A connected device (camera or card).
 */
export type DeviceView = { id: string, label: string, transport: TransportView, profileId: string, profileName: string, assetCount: number, };
