// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaKind } from "./MediaKind";

/**
 * One file of an asset (e.g. the CR3 of a RAW + JPEG pair).
 */
export type FileView = { name: string, 
/**
 * Device-relative path.
 */
path: string, kind: MediaKind, size: number | null, };
