// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupView } from "./GroupView";

/**
 * Result of scanning a local folder (Task 2 demo).
 */
export type FolderScan = { sourceLabel: string, profileId: string, profileName: string, groups: Array<GroupView>, };
