// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderMode } from "./FolderMode";
import type { SimpleFolders } from "./SimpleFolders";

export type FolderSettings = { mode: FolderMode, simple: SimpleFolders, 
/**
 * Folder template for the advanced mode, e.g. `{yyyy}-{MM}-{dd}/{file}`.
 */
template: string, };
