// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormatMode } from "./FormatMode";
import type { SaveFormats } from "./SaveFormats";

export type FormatSettings = { mode: FormatMode, uniform: SaveFormats, 
/**
 * Six entries indexed by stars: 0 = unrated, 1–5 = ★1–★5.
 */
perRating: Array<SaveFormats>, };
