// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileView } from "./FileView";

/**
 * Files grouped into one shot, without metadata.
 */
export type GroupView = { key: string, name: string, files: Array<FileView>, };
