// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaCategory } from "./MediaCategory";

/**
 * What to import from a device (the import dialog's choices).
 */
export type ImportRequest = { deviceId: string, 
/**
 * Stars to include: 0 = unrated, 1–5.
 */
ratings: Array<number>, media: Array<MediaCategory>, };
