// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderSettings } from "./FolderSettings";
import type { FormatSettings } from "./FormatSettings";

/**
 * Default import settings (edited in the Import Settings pane).
 */
export type ImportSettings = { formats: FormatSettings, 
/**
 * Destination root folder; `null` until chosen.
 */
destinationRoot: string | null, folders: FolderSettings, };
