// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportState } from "./ImportState";

/**
 * Progress of an import job, broadcast to every window while it runs.
 */
export type ImportProgress = { jobId: string, deviceId: string, state: ImportState, filesDone: number, filesTotal: number, bytesDone: number, bytesTotal: number, currentFile: string | null, error: string | null, };
