// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Media categories offered in the import dialog.
 */
export type MediaCategory = "image" | "video" | "metadata";
