// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The role of a file within an asset (a shot).
 */
export type MediaKind = "raw" | "heif" | "jpeg" | "video" | "sidecar";
