// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the effective rating comes from.
 */
export type RatingSource = "camera" | "app";
