// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sets (or clears, with `null`) the rating of several assets.
 */
export type RatingUpdate = { assetIds: Array<string>, rating: number | null, };
