// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which image files of a shot to save. HEIF counts as "JPG" (a developed image).
 */
export type SaveFormats = "rawOnly" | "rawAndJpeg" | "jpegOnly";
