// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Checkbox-based folder layout; converted to a template.
 */
export type SimpleFolders = { byDate: boolean, byHour: boolean, byRating: boolean, splitRawJpeg: boolean, };
