// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a device is connected, as shown in the UI.
 */
export type TransportView = "mtp" | "massStorage" | "vendor";
