//! The [`DeviceSource`] trait and the types it exchanges.

use std::io::Read;
use std::path::PathBuf;
use std::time::SystemTime;

use bytes::Bytes;

use crate::path::{PathError, VPath};

/// Identifies a connected device for as long as it stays connected.
///
/// Not stable across reconnections (MTP object and device handles change),
/// so it must never be persisted as an asset identity.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct DeviceId(pub String);

/// How the device is connected.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Transport {
    Mtp,
    MassStorage,
    /// A vendor SDK connection, named by the SDK (future extension).
    Vendor(String),
}

/// What is known about a device before reading any file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeviceInfo {
    pub id: DeviceId,
    pub transport: Transport,
    /// Human readable name (volume label, MTP friendly name, folder name).
    pub label: String,
    /// USB vendor ID when known (not available for card readers).
    pub usb_vendor_id: Option<u16>,
    pub manufacturer: Option<String>,
    pub model: Option<String>,
    pub serial: Option<String>,
}

bitflags::bitflags! {
    /// Optional abilities of a source. The UI enables features from these
    /// flags rather than from the transport type.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub struct SourceCaps: u32 {
        /// `read_range` reads only the requested bytes (no full download).
        const RANGE_READ   = 1 << 0;
        /// `device_thumbnail` can return a thumbnail generated by the device.
        const DEVICE_THUMB = 1 << 1;
        /// `local_path` returns a real file path (e.g. SD card).
        const LOCAL_PATH   = 1 << 2;
    }
}

/// Opaque, source-specific reference to a file or directory.
///
/// For file systems this is the path; for MTP it is an object ID. Valid only
/// while the device stays connected.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ObjRef(pub String);

impl ObjRef {
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EntryKind {
    File,
    Dir,
}

/// A listed file or directory.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Entry {
    pub obj: ObjRef,
    pub path: VPath,
    pub kind: EntryKind,
    /// Size in bytes, for files when known.
    pub size: Option<u64>,
    pub modified: Option<SystemTime>,
}

impl Entry {
    pub fn is_dir(&self) -> bool {
        self.kind == EntryKind::Dir
    }

    pub fn is_file(&self) -> bool {
        self.kind == EntryKind::File
    }
}

/// Device attach / detach notifications (produced by a `DeviceWatcher`, Task 12).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DeviceEvent {
    Attached(DeviceInfo),
    Detached(DeviceId),
}

#[derive(Debug, thiserror::Error)]
pub enum SourceError {
    #[error("not found: {0}")]
    NotFound(String),
    #[error("not a directory: {0}")]
    NotADirectory(String),
    #[error("not supported by this source: {0}")]
    Unsupported(&'static str),
    #[error("device disconnected")]
    Disconnected,
    #[error(transparent)]
    Path(#[from] PathError),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
}

pub type Result<T> = std::result::Result<T, SourceError>;

/// Read-only access to the files on a device.
pub trait DeviceSource: Send + Sync {
    fn info(&self) -> &DeviceInfo;

    fn caps(&self) -> SourceCaps;

    /// Lists the direct children of `dir`, sorted by path.
    fn list(&self, dir: &VPath) -> Result<Vec<Entry>>;

    /// Reads up to `len` bytes starting at `offset`. Returns fewer bytes when
    /// the range extends past the end of the file.
    fn read_range(&self, obj: &ObjRef, offset: u64, len: u64) -> Result<Bytes>;

    /// Opens the whole file as a stream (used for copying).
    fn open_stream(&self, obj: &ObjRef) -> Result<Box<dyn Read + Send>>;

    /// A thumbnail produced by the device itself, if supported.
    fn device_thumbnail(&self, _obj: &ObjRef) -> Result<Option<Bytes>> {
        Ok(None)
    }

    /// The local file path, for sources with [`SourceCaps::LOCAL_PATH`].
    fn local_path(&self, _obj: &ObjRef) -> Option<PathBuf> {
        None
    }
}
